name: CICD-bloated
on:
  push:
    paths: 'CICD-bloated/Dockerfile'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bobbintb
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get UnRAID version
        run: |
          cd ./CICD-bloated
          docker build -t bobbintb/unraid-cicd-bloated .
          docker push bobbintb/unraid-cicd-bloated
          VERSION_ID=$(docker run --rm bobbintb/unraid-cicd-bloated /bin/bash -c ". /etc/os-release && echo \$VERSION_ID")
          docker build -t bobbintb/unraid-cicd-bloated:$VERSION_ID .
          docker push bobbintb/unraid-cicd-bloated:$VERSION_ID
