name: rmlint
on:
  push:
    paths: 'rmlint/Dockerfile'
  workflow_dispatch:
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bobbintb
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get UnRAID version
        run: |
          docker build -t bobbintb/docker-rmlint-unraid:dev .
          docker push bobbintb/docker-rmlint-unraid:dev
